from linkingFunctions import *


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.Qt import Qt


class Ui_janela(object):
    def setupUi(self, janela):
        janela.setObjectName("janela")
        janela.resize(280, 430)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(janela.sizePolicy().hasHeightForWidth())
        janela.setSizePolicy(sizePolicy)
        janela.setMinimumSize(QtCore.QSize(280, 430))
        janela.setMaximumSize(QtCore.QSize(280, 430))
        font = QtGui.QFont()
        font.setKerning(True)
        janela.setFont(font)
        janela.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        janela.setWindowTitle("CalcFox")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/noone/Desktop/dev/python/calculadora/fox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        janela.setWindowIcon(icon)
        janela.setStatusTip("")
        janela.setStyleSheet("QPushButton:hover{background: rgba(0, 194, 255, 0.12)}")
        janela.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        janela.setAnimated(True)
        janela.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(janela)
        self.centralwidget.setObjectName("centralwidget")
        self.button7number = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: addingNumber(7,ui))
        self.button7number.setGeometry(QtCore.QRect(0, 150, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.button7number.setFont(font)
        self.button7number.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button7number.setCheckable(False)
        self.button7number.setChecked(False)
        self.button7number.setAutoRepeat(False)
        self.button7number.setAutoExclusive(True)
        self.button7number.setDefault(True)
        self.button7number.setFlat(True)
        self.button7number.setObjectName("button7number")
        self.button8number = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: addingNumber(8,ui))
        self.button8number.setGeometry(QtCore.QRect(70, 150, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.button8number.setFont(font)
        self.button8number.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button8number.setCheckable(False)
        self.button8number.setChecked(False)
        self.button8number.setAutoRepeat(False)
        self.button8number.setAutoExclusive(True)
        self.button8number.setDefault(True)
        self.button8number.setFlat(True)
        self.button8number.setObjectName("button8number")
        self.button9number = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: addingNumber(9,ui))
        self.button9number.setGeometry(QtCore.QRect(140, 150, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.button9number.setFont(font)
        self.button9number.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button9number.setCheckable(False)
        self.button9number.setChecked(False)
        self.button9number.setAutoRepeat(False)
        self.button9number.setAutoExclusive(True)
        self.button9number.setDefault(True)
        self.button9number.setFlat(True)
        self.button9number.setObjectName("button9number")
        self.buttoninv = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: inverting(ui))
        self.buttoninv.setGeometry(QtCore.QRect(210, 150, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.buttoninv.setFont(font)
        self.buttoninv.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttoninv.setCheckable(False)
        self.buttoninv.setChecked(False)
        self.buttoninv.setAutoRepeat(False)
        self.buttoninv.setAutoExclusive(True)
        self.buttoninv.setAutoDefault(False)
        self.buttoninv.setDefault(True)
        self.buttoninv.setFlat(True)
        self.buttoninv.setObjectName("buttoninv")
        self.button6number = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: addingNumber(6,ui))
        self.button6number.setGeometry(QtCore.QRect(140, 220, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.button6number.setFont(font)
        self.button6number.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button6number.setCheckable(False)
        self.button6number.setChecked(False)
        self.button6number.setAutoRepeat(False)
        self.button6number.setAutoExclusive(True)
        self.button6number.setDefault(True)
        self.button6number.setFlat(True)
        self.button6number.setObjectName("button6number")
        self.button3number = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: addingNumber(3,ui))
        self.button3number.setGeometry(QtCore.QRect(140, 290, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.button3number.setFont(font)
        self.button3number.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button3number.setCheckable(False)
        self.button3number.setChecked(False)
        self.button3number.setAutoRepeat(False)
        self.button3number.setAutoExclusive(True)
        self.button3number.setDefault(True)
        self.button3number.setFlat(True)
        self.button3number.setObjectName("button3number")
        self.button2number = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: addingNumber(2,ui))
        self.button2number.setGeometry(QtCore.QRect(70, 290, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.button2number.setFont(font)
        self.button2number.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button2number.setCheckable(False)
        self.button2number.setChecked(False)
        self.button2number.setAutoRepeat(False)
        self.button2number.setAutoExclusive(True)
        self.button2number.setDefault(True)
        self.button2number.setFlat(True)
        self.button2number.setObjectName("button2number")
        self.button5number = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: addingNumber(5,ui))
        self.button5number.setGeometry(QtCore.QRect(70, 220, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.button5number.setFont(font)
        self.button5number.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button5number.setCheckable(False)
        self.button5number.setChecked(False)
        self.button5number.setAutoRepeat(False)
        self.button5number.setAutoExclusive(True)
        self.button5number.setDefault(True)
        self.button5number.setFlat(True)
        self.button5number.setObjectName("button5number")
        self.button4number = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: addingNumber(4,ui))
        self.button4number.setGeometry(QtCore.QRect(0, 220, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.button4number.setFont(font)
        self.button4number.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button4number.setCheckable(False)
        self.button4number.setChecked(False)
        self.button4number.setAutoRepeat(False)
        self.button4number.setAutoExclusive(True)
        self.button4number.setDefault(True)
        self.button4number.setFlat(True)
        self.button4number.setObjectName("button4number")
        self.buttoncomma = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: addingComma(ui))
        self.buttoncomma.setGeometry(QtCore.QRect(210, 220, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.buttoncomma.setFont(font)
        self.buttoncomma.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttoncomma.setStyleSheet("QPushbutton.hover{background: rgba(0,0,0,0.1)}")
        self.buttoncomma.setCheckable(False)
        self.buttoncomma.setChecked(False)
        self.buttoncomma.setAutoRepeat(False)
        self.buttoncomma.setAutoExclusive(True)
        self.buttoncomma.setDefault(True)
        self.buttoncomma.setFlat(True)
        self.buttoncomma.setObjectName("buttoncomma")
        self.button1number = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: addingNumber(1,ui))
        self.button1number.setGeometry(QtCore.QRect(0, 290, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.button1number.setFont(font)
        self.button1number.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button1number.setCheckable(False)
        self.button1number.setChecked(False)
        self.button1number.setAutoRepeat(False)
        self.button1number.setAutoExclusive(True)
        self.button1number.setDefault(True)
        self.button1number.setFlat(True)
        self.button1number.setObjectName("button1number")
        self.button0number = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: addingNumber(0,ui))
        self.button0number.setGeometry(QtCore.QRect(210, 290, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.button0number.setFont(font)
        self.button0number.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button0number.setCheckable(False)
        self.button0number.setChecked(False)
        self.button0number.setAutoRepeat(False)
        self.button0number.setAutoExclusive(True)
        self.button0number.setDefault(True)
        self.button0number.setFlat(True)
        self.button0number.setObjectName("button0number")
        self.buttonequals = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: calculate(ui))
        self.buttonequals.setGeometry(QtCore.QRect(140, 360, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.buttonequals.setFont(font)
        self.buttonequals.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonequals.setCheckable(False)
        self.buttonequals.setChecked(False)
        self.buttonequals.setAutoRepeat(False)
        self.buttonequals.setAutoExclusive(True)
        self.buttonequals.setDefault(True)
        self.buttonequals.setFlat(True)
        self.buttonequals.setObjectName("buttonequals")
        self.buttonmulti = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: addingOperation("x",ui))
        self.buttonmulti.setEnabled(True)
        self.buttonmulti.setGeometry(QtCore.QRect(140, 80, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.buttonmulti.setFont(font)
        self.buttonmulti.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonmulti.setCheckable(False)
        self.buttonmulti.setChecked(False)
        self.buttonmulti.setAutoRepeat(False)
        self.buttonmulti.setAutoExclusive(False)
        self.buttonmulti.setAutoDefault(False)
        self.buttonmulti.setDefault(True)
        self.buttonmulti.setFlat(True)
        self.buttonmulti.setObjectName("buttonmulti")
        self.buttondiv = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: addingOperation("/",ui))
        self.buttondiv.setGeometry(QtCore.QRect(210, 80, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.buttondiv.setFont(font)
        self.buttondiv.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttondiv.setCheckable(False)
        self.buttondiv.setChecked(False)
        self.buttondiv.setAutoRepeat(False)
        self.buttondiv.setAutoExclusive(True)
        self.buttondiv.setAutoDefault(False)
        self.buttondiv.setDefault(True)
        self.buttondiv.setFlat(True)
        self.buttondiv.setObjectName("buttondiv")
        self.buttonminus = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: addingOperation("-",ui))
        self.buttonminus.setGeometry(QtCore.QRect(70, 80, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.buttonminus.setFont(font)
        self.buttonminus.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonminus.setCheckable(False)
        self.buttonminus.setChecked(False)
        self.buttonminus.setAutoRepeat(False)
        self.buttonminus.setAutoExclusive(True)
        self.buttonminus.setDefault(True)
        self.buttonminus.setFlat(True)
        self.buttonminus.setObjectName("buttonminus")
        self.buttonplus = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: addingOperation("+",ui))
        self.buttonplus.setGeometry(QtCore.QRect(0, 80, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.buttonplus.setFont(font)
        self.buttonplus.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonplus.setCheckable(False)
        self.buttonplus.setChecked(False)
        self.buttonplus.setAutoRepeat(False)
        self.buttonplus.setAutoExclusive(True)
        self.buttonplus.setAutoDefault(False)
        self.buttonplus.setDefault(True)
        self.buttonplus.setFlat(True)
        self.buttonplus.setObjectName("buttonplus")
        self.buttonCLR = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: clearing(ui))
        self.buttonCLR.setGeometry(QtCore.QRect(0, 360, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.buttonCLR.setFont(font)
        self.buttonCLR.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonCLR.setCheckable(False)
        self.buttonCLR.setChecked(False)
        self.buttonCLR.setAutoRepeat(False)
        self.buttonCLR.setAutoExclusive(True)
        self.buttonCLR.setDefault(True)
        self.buttonCLR.setFlat(True)
        self.buttonCLR.setObjectName("buttonCLR")
        self.buttonbackspace = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: erasing(ui))
        self.buttonbackspace.setGeometry(QtCore.QRect(70, 360, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setKerning(True)
        self.buttonbackspace.setFont(font)
        self.buttonbackspace.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonbackspace.setCheckable(False)
        self.buttonbackspace.setChecked(False)
        self.buttonbackspace.setAutoRepeat(False)
        self.buttonbackspace.setAutoExclusive(True)
        self.buttonbackspace.setDefault(True)
        self.buttonbackspace.setFlat(True)
        self.buttonbackspace.setObjectName("buttonbackspace")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 281, 80))
        font = QtGui.QFont()
        font.setBold(False)
        font.setKerning(True)
        self.frame.setFont(font)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgba(0, 0, 0, 0.1);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.calcscreen = QtWidgets.QLabel(self.frame)
        self.calcscreen.setGeometry(QtCore.QRect(0, 0, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setKerning(True)
        self.calcscreen.setFont(font)
        self.calcscreen.setFocusPolicy(QtCore.Qt.NoFocus)
        self.calcscreen.setStyleSheet("background-color: none;")
        self.calcscreen.setLineWidth(1)
        self.calcscreen.setTextFormat(QtCore.Qt.RichText)
        self.calcscreen.setScaledContents(False)
        self.calcscreen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.calcscreen.setWordWrap(False)
        self.calcscreen.setIndent(5)
        self.calcscreen.setOpenExternalLinks(False)
        self.calcscreen.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.calcscreen.setObjectName("calcscreen")
        janela.setCentralWidget(self.centralwidget)

        self.retranslateUi(janela)
        QtCore.QMetaObject.connectSlotsByName(janela)

    def retranslateUi(self, janela):
        _translate = QtCore.QCoreApplication.translate
        self.button7number.setText(_translate("janela", "7"))
        self.button8number.setText(_translate("janela", "8"))
        self.button9number.setText(_translate("janela", "9"))
        self.buttoninv.setText(_translate("janela", "±"))
        self.button6number.setText(_translate("janela", "6"))
        self.button3number.setText(_translate("janela", "3"))
        self.button2number.setText(_translate("janela", "2"))
        self.button5number.setText(_translate("janela", "5"))
        self.button4number.setText(_translate("janela", "4"))
        self.buttoncomma.setText(_translate("janela", ","))
        self.button1number.setText(_translate("janela", "1"))
        self.button0number.setText(_translate("janela", "0"))
        self.buttonequals.setText(_translate("janela", "="))
        self.buttonmulti.setText(_translate("janela", "X"))
        self.buttondiv.setText(_translate("janela", "÷"))
        self.buttonminus.setText(_translate("janela", "-"))
        self.buttonplus.setText(_translate("janela", "+"))
        self.buttonCLR.setText(_translate("janela", "CLR"))
        self.buttonbackspace.setText(_translate("janela", "←"))
        self.calcscreen.setText(_translate("janela", "0"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    janela = QtWidgets.QMainWindow()
    ui = Ui_janela()

    ui.setupUi(janela)
    janela.show()
    sys.exit(app.exec_())
